# Generated by Django 3.1.7 on 2021-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='customers',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='customers',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
    ]
